version: '3.8'

services:

  todomicroservice:
    container_name: todomicroservice
    ports:
      - '3000:3000'
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - some-net


  mongo:
    container_name: microservice-mongo
    image: mongo
    restart: always
    command: mongod --port 27018
    ports:
      - 27018:27018
    environment:
      MONGO_INITDB_ROOT_USERNAME: tugrul
      MONGO_INITDB_ROOT_PASSWORD: mercan
    networks:
      - some-net

  mongo-express:
    image: mongo-express
    container_name: microservice-mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:

      ME_CONFIG_BASICAUTH_USERNAME: tugrul
      ME_CONFIG_BASICAUTH_PASSWORD: mercan
      ME_CONFIG_MONGODB_PORT: 27018
      ME_CONFIG_MONGODB_ADMINUSERNAME: tugrul
      ME_CONFIG_MONGODB_ADMINPASSWORD: mercan
      ME_CONFIG_MONGODB_URL: mongodb://tugrul:mercan@mongo:27018/
    networks:
      - some-net
networks:
  some-net:

